#!/bin/sh

set -e

tmp=$(mktemp)
trap "rm $tmp" EXIT

runcpu "$@" | tee $tmp

# Check for errors.
# If error is found exit with non-zero exit code.
# Otherwise, exit cleanly.
! grep -q '^Error:' $tmp
